/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g
 *     -                            On : 2012-11-16 17:54:53
 *     -                for the parser : MAliceParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MAliceParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMAliceParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMAliceParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMAliceParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMAliceParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   MAliceParserTokenNames[23+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "CHARACTER_LITERAL",
        (pANTLR3_UINT8) "DECIMAL_NUMBER",
        (pANTLR3_UINT8) "LETTER",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'.'",
        (pANTLR3_UINT8) "'0'",
        (pANTLR3_UINT8) "'9'",
        (pANTLR3_UINT8) "'Alice found'",
        (pANTLR3_UINT8) "'The'",
        (pANTLR3_UINT8) "'and'",
        (pANTLR3_UINT8) "'but'",
        (pANTLR3_UINT8) "'closed'",
        (pANTLR3_UINT8) "'contained a'",
        (pANTLR3_UINT8) "'letter'",
        (pANTLR3_UINT8) "'looking-glass'",
        (pANTLR3_UINT8) "'number'",
        (pANTLR3_UINT8) "'opened'",
        (pANTLR3_UINT8) "'room'",
        (pANTLR3_UINT8) "'then'",
        (pANTLR3_UINT8) "'~'"
       };

const char *
ruleNames[] =
	{
		"invalidRule", "unary_operator", "program", "function", "function_type", 
		"function_invocation", "function_argument", "block_unit", "type", "return_type_clause", 
		"split", "constant", "identifier", "return", "function_invocation_argument_list", 
		"function_argument_list"
	};

 
static ANTLR3_UINT32 ruleLevel = 0;
static ANTLR3_UINT32 getRuleLevel()
{
	return ruleLevel;
}
static void incRuleLevel()
{
	ruleLevel++;
}
static void decRuleLevel()
{
	ruleLevel--;
}
static ANTLR3_BOOLEAN
evalPredicate(pMAliceParser ctx, ANTLR3_BOOLEAN result, const char * predicate)
{
    DBG->semanticPredicate(DBG, result, predicate);
    return result;
}


// Forward declare the locally static matching functions we have generated.
//
static 
 void
	identifier    (pMAliceParser ctx);
static 
 void
	split    (pMAliceParser ctx);
static 
 void
	type    (pMAliceParser ctx);
static 
 void
	unary_operator    (pMAliceParser ctx);
static 
 void
	constant    (pMAliceParser ctx);
static 
 void
	program    (pMAliceParser ctx);
static 
 void
	function    (pMAliceParser ctx);
static 
 void
	function_type    (pMAliceParser ctx);
static 
 void
	function_argument_list    (pMAliceParser ctx);
static 
 void
	function_argument    (pMAliceParser ctx);
static 
 void
	return_type_clause    (pMAliceParser ctx);
static 
 void
	block_unit    (pMAliceParser ctx);
static 
 void
	function_invocation    (pMAliceParser ctx);
static 
 void
	function_invocation_argument_list    (pMAliceParser ctx);
static 
 void
	return    (pMAliceParser ctx);
static void	MAliceParserFree(pMAliceParser ctx);
static void     MAliceParserReset (pMAliceParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new MAliceParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMAliceParser
MAliceParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return MAliceParserNewSSD(instream, NULL);
}

/** \brief Create a new MAliceParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMAliceParser
MAliceParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMAliceParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pMAliceParser) ANTLR3_CALLOC(1, sizeof(MAliceParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MAliceParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our MAliceParser interface
     */
    ctx->identifier	= identifier;
    ctx->split	= split;
    ctx->type	= type;
    ctx->unary_operator	= unary_operator;
    ctx->constant	= constant;
    ctx->program	= program;
    ctx->function	= function;
    ctx->function_type	= function_type;
    ctx->function_argument_list	= function_argument_list;
    ctx->function_argument	= function_argument;
    ctx->return_type_clause	= return_type_clause;
    ctx->block_unit	= block_unit;
    ctx->function_invocation	= function_invocation;
    ctx->function_invocation_argument_list	= function_invocation_argument_list;
    ctx->return	= return;
    ctx->free			= MAliceParserFree;
    ctx->reset			= MAliceParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = MAliceParserTokenNames;

    {
    	// DEBUG MODE code
    	//
    	pANTLR3_DEBUG_EVENT_LISTENER	 proxy;
    	proxy = antlr3DebugListenerNew();
    	proxy->grammarFileName = INPUT->tokenSource->strFactory->newStr8(INPUT->tokenSource->strFactory, (pANTLR3_UINT8)ctx->getGrammarFileName());

    	PARSER->setDebugListener(PARSER, proxy);

    	// Try to connect to the debugger (waits forever for a connection)
    	//
    	proxy->handshake(proxy);

    	// End DEBUG MODE code
    	//
    }


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
MAliceParserReset (pMAliceParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 MAliceParserFree(pMAliceParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return MAliceParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LETTER_in_identifier27  */
static	ANTLR3_BITWORD FOLLOW_LETTER_in_identifier27_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000042) };
static  ANTLR3_BITSET_LIST FOLLOW_LETTER_in_identifier27	= { FOLLOW_LETTER_in_identifier27_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_unary_operator123  */
static	ANTLR3_BITWORD FOLLOW_26_in_unary_operator123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_unary_operator123	= { FOLLOW_26_in_unary_operator123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_in_program151  */
static	ANTLR3_BITWORD FOLLOW_function_in_program151_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008002) };
static  ANTLR3_BITSET_LIST FOLLOW_function_in_program151	= { FOLLOW_function_in_program151_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_function159  */
static	ANTLR3_BITWORD FOLLOW_15_in_function159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001200000) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_function159	= { FOLLOW_15_in_function159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_type_in_function161  */
static	ANTLR3_BITWORD FOLLOW_function_type_in_function161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_function_type_in_function161	= { FOLLOW_function_type_in_function161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_identifier_in_function163  */
static	ANTLR3_BITWORD FOLLOW_identifier_in_function163_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_identifier_in_function163	= { FOLLOW_identifier_in_function163_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_function165  */
static	ANTLR3_BITWORD FOLLOW_8_in_function165_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000500200) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_function165	= { FOLLOW_8_in_function165_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_argument_list_in_function167  */
static	ANTLR3_BITWORD FOLLOW_function_argument_list_in_function167_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_function_argument_list_in_function167	= { FOLLOW_function_argument_list_in_function167_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_function170  */
static	ANTLR3_BITWORD FOLLOW_9_in_function170_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000880000) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_function170	= { FOLLOW_9_in_function170_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_return_type_clause_in_function172  */
static	ANTLR3_BITWORD FOLLOW_return_type_clause_in_function172_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_return_type_clause_in_function172	= { FOLLOW_return_type_clause_in_function172_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_unit_in_function175  */
static	ANTLR3_BITWORD FOLLOW_block_unit_in_function175_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_unit_in_function175	= { FOLLOW_block_unit_in_function175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_argument_in_function_argument_list200  */
static	ANTLR3_BITWORD FOLLOW_function_argument_in_function_argument_list200_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_function_argument_in_function_argument_list200	= { FOLLOW_function_argument_in_function_argument_list200_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_function_argument_list202  */
static	ANTLR3_BITWORD FOLLOW_10_in_function_argument_list202_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000500000) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_function_argument_list202	= { FOLLOW_10_in_function_argument_list202_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_argument_in_function_argument_list206  */
static	ANTLR3_BITWORD FOLLOW_function_argument_in_function_argument_list206_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_function_argument_in_function_argument_list206	= { FOLLOW_function_argument_in_function_argument_list206_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_type_in_function_argument216  */
static	ANTLR3_BITWORD FOLLOW_type_in_function_argument216_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_type_in_function_argument216	= { FOLLOW_type_in_function_argument216_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_identifier_in_function_argument218  */
static	ANTLR3_BITWORD FOLLOW_identifier_in_function_argument218_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_identifier_in_function_argument218	= { FOLLOW_identifier_in_function_argument218_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_return_type_clause228  */
static	ANTLR3_BITWORD FOLLOW_19_in_return_type_clause228_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000500000) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_return_type_clause228	= { FOLLOW_19_in_return_type_clause228_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_type_in_return_type_clause230  */
static	ANTLR3_BITWORD FOLLOW_type_in_return_type_clause230_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_type_in_return_type_clause230	= { FOLLOW_type_in_return_type_clause230_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_block_unit240  */
static	ANTLR3_BITWORD FOLLOW_23_in_block_unit240_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_block_unit240	= { FOLLOW_23_in_block_unit240_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_block_unit242  */
static	ANTLR3_BITWORD FOLLOW_18_in_block_unit242_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_block_unit242	= { FOLLOW_18_in_block_unit242_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_identifier_in_function_invocation252  */
static	ANTLR3_BITWORD FOLLOW_identifier_in_function_invocation252_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_identifier_in_function_invocation252	= { FOLLOW_identifier_in_function_invocation252_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_function_invocation254  */
static	ANTLR3_BITWORD FOLLOW_8_in_function_invocation254_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000230) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_function_invocation254	= { FOLLOW_8_in_function_invocation254_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_invocation_argument_list_in_function_invocation256  */
static	ANTLR3_BITWORD FOLLOW_function_invocation_argument_list_in_function_invocation256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_function_invocation_argument_list_in_function_invocation256	= { FOLLOW_function_invocation_argument_list_in_function_invocation256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_function_invocation259  */
static	ANTLR3_BITWORD FOLLOW_9_in_function_invocation259_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_function_invocation259	= { FOLLOW_9_in_function_invocation259_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_constant_in_function_invocation_argument_list270  */
static	ANTLR3_BITWORD FOLLOW_constant_in_function_invocation_argument_list270_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_constant_in_function_invocation_argument_list270	= { FOLLOW_constant_in_function_invocation_argument_list270_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_function_invocation_argument_list272  */
static	ANTLR3_BITWORD FOLLOW_10_in_function_invocation_argument_list272_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000030) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_function_invocation_argument_list272	= { FOLLOW_10_in_function_invocation_argument_list272_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_constant_in_function_invocation_argument_list276  */
static	ANTLR3_BITWORD FOLLOW_constant_in_function_invocation_argument_list276_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_constant_in_function_invocation_argument_list276	= { FOLLOW_constant_in_function_invocation_argument_list276_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_return288  */
static	ANTLR3_BITWORD FOLLOW_14_in_return288_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000030) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_return288	= { FOLLOW_14_in_return288_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_constant_in_return290  */
static	ANTLR3_BITWORD FOLLOW_constant_in_return290_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_constant_in_return290	= { FOLLOW_constant_in_return290_bits, 1	};



/* =========================================================================
 * DFA tables for the parser
 */
/** Static dfa state tables for Cyclic dfa:
 *    ()* loopback of 100:4: ( function_argument ',' )*
 */
static const ANTLR3_INT32 dfa5_eot[6] =
    {
	-1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa5_eof[6] =
    {
	-1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa5_min[6] =
    {
	20, 6, 6, 6, -1, -1
    };
static const ANTLR3_INT32 dfa5_max[6] =
    {
	22, 6, 10, 10, -1, -1
    };
static const ANTLR3_INT32 dfa5_accept[6] =
    {
	-1, -1, -1, -1, 2, 1
    };
static const ANTLR3_INT32 dfa5_special[6] =
    {
	-1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa5_T_empty	    NULL

static const ANTLR3_INT32 dfa5_T0[] =
    {
	1, -1, 1
    };

static const ANTLR3_INT32 dfa5_T1[] =
    {
	3, -1, -1, 4, 5
    };

static const ANTLR3_INT32 dfa5_T2[] =
    {
	2
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa5_transitions[] =
{
    dfa5_T0, dfa5_T2, dfa5_T1, dfa5_T1, NULL, NULL
};

//static void
//dfaError(pMAliceParser ctx)
//{
//    DBG->recognitionException(DBG, EXCEPTION);
//}

/* Declare tracking structure for Cyclic DFA 5
 */
static
ANTLR3_CYCLIC_DFA cdfa5
    =	{
	    5,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"()* loopback of 100:4: ( function_argument ',' )*",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa5_eot,	    /* EOT table			    */
	    dfa5_eof,	    /* EOF table			    */
	    dfa5_min,	    /* Minimum tokens for each state    */
	    dfa5_max,	    /* Maximum tokens for each state    */
	    dfa5_accept,	/* Accept table			    */
	    dfa5_special,	/* Special transition states	    */
	    dfa5_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 5
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the parser
 */

/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start identifier
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:46:1: identifier : LETTER ( LETTER | '0' .. '9' )* ;
 */
static void
identifier(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"identifier");
    incRuleLevel();
    DBG->location(DBG, 46, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:47:2: ( LETTER ( LETTER | '0' .. '9' )* )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:47:4: LETTER ( LETTER | '0' .. '9' )*
        {
            DBG->location(DBG, 47, 4);
             MATCHT(LETTER, &FOLLOW_LETTER_in_identifier27);
            if  (HASEXCEPTION())
            {
                goto ruleidentifierEx;
            }

            DBG->location(DBG, 47, 11);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:47:11: ( LETTER | '0' .. '9' )*

            DBG->enterSubRule(DBG, 1);

            for (;;)
            {
                int alt1=2;
                DBG->enterDecision(DBG, 1);

                switch ( LA(1) )
                {
                case LETTER:
                	{
                		alt1=1;
                	}
                    break;

                }

                DBG->exitDecision(DBG, 1);

                switch (alt1)
                {
            	case 1:
            	    DBG->enterAlt(DBG, 1);

            	    // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:
            	    {
            	        DBG->location(DBG, 47, 11);
            	        if ( LA(1) == LETTER )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            DBG->recognitionException(DBG, EXCEPTION);
            	            goto ruleidentifierEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */
            DBG->exitSubRule(DBG, 1);


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleidentifierEx; /* Prevent compiler warnings */
    ruleidentifierEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 48, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"identifier");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end identifier */

/**
 * $ANTLR start split
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:67:1: split : ( '.' | ',' | 'then' | 'and' | 'but' ) ;
 */
static void
split(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"split");
    incRuleLevel();
    DBG->location(DBG, 67, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:67:8: ( ( '.' | ',' | 'then' | 'and' | 'but' ) )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:
        {
            DBG->location(DBG, 67, 8);
            if ( ((LA(1) >= 10) && (LA(1) <= 11)) || ((LA(1) >= 16) && (LA(1) <= 17)) || LA(1) == 25 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                DBG->recognitionException(DBG, EXCEPTION);
                goto rulesplitEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulesplitEx; /* Prevent compiler warnings */
    rulesplitEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 67, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"split");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end split */

/**
 * $ANTLR start type
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:77:1: type : ( 'number' | 'letter' );
 */
static void
type(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"type");
    incRuleLevel();
    DBG->location(DBG, 77, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:77:7: ( 'number' | 'letter' )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:
        {
            DBG->location(DBG, 77, 7);
            if ( LA(1) == 20 || LA(1) == 22 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                DBG->recognitionException(DBG, EXCEPTION);
                goto ruletypeEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletypeEx; /* Prevent compiler warnings */
    ruletypeEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 79, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"type");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end type */

/**
 * $ANTLR start unary_operator
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:81:1: unary_operator : '~' ;
 */
static void
unary_operator(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"unary_operator");
    incRuleLevel();
    DBG->location(DBG, 81, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:82:2: ( '~' )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:82:4: '~'
        {
            DBG->location(DBG, 82, 4);
             MATCHT(26, &FOLLOW_26_in_unary_operator123);
            if  (HASEXCEPTION())
            {
                goto ruleunary_operatorEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleunary_operatorEx; /* Prevent compiler warnings */
    ruleunary_operatorEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 83, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"unary_operator");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end unary_operator */

/**
 * $ANTLR start constant
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:85:1: constant : ( DECIMAL_NUMBER | CHARACTER_LITERAL );
 */
static void
constant(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"constant");
    incRuleLevel();
    DBG->location(DBG, 85, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:85:9: ( DECIMAL_NUMBER | CHARACTER_LITERAL )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:
        {
            DBG->location(DBG, 85, 9);
            if ( ((LA(1) >= CHARACTER_LITERAL) && (LA(1) <= DECIMAL_NUMBER)) )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                DBG->recognitionException(DBG, EXCEPTION);
                goto ruleconstantEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleconstantEx; /* Prevent compiler warnings */
    ruleconstantEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 87, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"constant");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end constant */

/**
 * $ANTLR start program
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:92:1: program : ( function )+ ;
 */
static void
program(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"program");
    incRuleLevel();
    DBG->location(DBG, 92, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:92:9: ( ( function )+ )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:92:11: ( function )+
        {
            DBG->location(DBG, 92, 11);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:92:11: ( function )+
            {
                int cnt2=0;
                DBG->enterSubRule(DBG, 2);


                for (;;)
                {
                    int alt2=2;
            	DBG->enterDecision(DBG, 2);

            	switch ( LA(1) )
            	{
            	case 15:
            		{
            			alt2=1;
            		}
            	    break;

            	}

            	DBG->exitDecision(DBG, 2);

            	switch (alt2)
            	{
            	    case 1:
            	        DBG->enterAlt(DBG, 1);

            	        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:92:11: function
            	        {
            	            DBG->location(DBG, 92, 11);
            	            FOLLOWPUSH(FOLLOW_function_in_program151);
            	            function(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogramEx;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt2 >= 1 )
            		{
            		    goto loop2;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		DBG->recognitionException(DBG, EXCEPTION);

            		goto ruleprogramEx;
            	}
            	cnt2++;
                }
                loop2: ;	/* Jump to here if this rule does not match */
                DBG->exitSubRule(DBG, 2);

            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 92, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"program");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end program */

/**
 * $ANTLR start function
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:1: function : 'The' function_type identifier '(' ( function_argument_list )? ')' ( return_type_clause )? block_unit ;
 */
static void
function(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"function");
    incRuleLevel();
    DBG->location(DBG, 94, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:9: ( 'The' function_type identifier '(' ( function_argument_list )? ')' ( return_type_clause )? block_unit )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:11: 'The' function_type identifier '(' ( function_argument_list )? ')' ( return_type_clause )? block_unit
        {
            DBG->location(DBG, 94, 11);
             MATCHT(15, &FOLLOW_15_in_function159);
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }

            DBG->location(DBG, 94, 17);
            FOLLOWPUSH(FOLLOW_function_type_in_function161);
            function_type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }

            DBG->location(DBG, 94, 31);
            FOLLOWPUSH(FOLLOW_identifier_in_function163);
            identifier(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }

            DBG->location(DBG, 94, 42);
             MATCHT(8, &FOLLOW_8_in_function165);
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }

            DBG->location(DBG, 94, 46);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:46: ( function_argument_list )?
            {
                int alt3=2;
                DBG->enterSubRule(DBG, 3);
                DBG->enterDecision(DBG, 3);

                switch ( LA(1) )
                {
                    case 20:
                    case 22:
                    	{
                    		alt3=1;
                    	}
                        break;
                }

                DBG->exitDecision(DBG, 3);

                switch (alt3)
                {
            	case 1:
            	    DBG->enterAlt(DBG, 1);

            	    // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:46: function_argument_list
            	    {
            	        DBG->location(DBG, 94, 46);
            	        FOLLOWPUSH(FOLLOW_function_argument_list_in_function167);
            	        function_argument_list(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }


            	    }
            	    break;

                }
                DBG->exitSubRule(DBG, 3);

            }
            DBG->location(DBG, 94, 70);
             MATCHT(9, &FOLLOW_9_in_function170);
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }

            DBG->location(DBG, 94, 74);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:74: ( return_type_clause )?
            {
                int alt4=2;
                DBG->enterSubRule(DBG, 4);
                DBG->enterDecision(DBG, 4);

                switch ( LA(1) )
                {
                    case 19:
                    	{
                    		alt4=1;
                    	}
                        break;
                }

                DBG->exitDecision(DBG, 4);

                switch (alt4)
                {
            	case 1:
            	    DBG->enterAlt(DBG, 1);

            	    // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:94:74: return_type_clause
            	    {
            	        DBG->location(DBG, 94, 74);
            	        FOLLOWPUSH(FOLLOW_return_type_clause_in_function172);
            	        return_type_clause(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }


            	    }
            	    break;

                }
                DBG->exitSubRule(DBG, 4);

            }
            DBG->location(DBG, 94, 94);
            FOLLOWPUSH(FOLLOW_block_unit_in_function175);
            block_unit(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunctionEx; /* Prevent compiler warnings */
    rulefunctionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 94, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"function");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end function */

/**
 * $ANTLR start function_type
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:95:1: function_type : ( 'room' | 'looking-glass' );
 */
static void
function_type(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"function_type");
    incRuleLevel();
    DBG->location(DBG, 95, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:96:2: ( 'room' | 'looking-glass' )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:
        {
            DBG->location(DBG, 96, 2);
            if ( LA(1) == 21 || LA(1) == 24 )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = NULL;

                DBG->recognitionException(DBG, EXCEPTION);
                goto rulefunction_typeEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunction_typeEx; /* Prevent compiler warnings */
    rulefunction_typeEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 98, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"function_type");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end function_type */

/**
 * $ANTLR start function_argument_list
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:99:1: function_argument_list : ( function_argument ',' )* function_argument ;
 */
static void
function_argument_list(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"function_argument_list");
    incRuleLevel();
    DBG->location(DBG, 99, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:100:2: ( ( function_argument ',' )* function_argument )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:100:4: ( function_argument ',' )* function_argument
        {
            DBG->location(DBG, 100, 4);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:100:4: ( function_argument ',' )*

            DBG->enterSubRule(DBG, 5);

            for (;;)
            {
                int alt5=2;
                DBG->enterDecision(DBG, 5);

                alt5 = cdfa5.predict(ctx, RECOGNIZER, ISTREAM, &cdfa5);
                if  (HASEXCEPTION())
                {
                	DBG->recognitionException(DBG, EXCEPTION);
                    goto rulefunction_argument_listEx;
                }
                if  (HASEXCEPTION())
                {
                    goto rulefunction_argument_listEx;
                }

                DBG->exitDecision(DBG, 5);

                switch (alt5)
                {
            	case 1:
            	    DBG->enterAlt(DBG, 1);

            	    // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:100:5: function_argument ','
            	    {
            	        DBG->location(DBG, 100, 5);
            	        FOLLOWPUSH(FOLLOW_function_argument_in_function_argument_list200);
            	        function_argument(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunction_argument_listEx;
            	        }

            	        DBG->location(DBG, 100, 23);
            	         MATCHT(10, &FOLLOW_10_in_function_argument_list202);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunction_argument_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */
            DBG->exitSubRule(DBG, 5);

            DBG->location(DBG, 100, 29);
            FOLLOWPUSH(FOLLOW_function_argument_in_function_argument_list206);
            function_argument(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunction_argument_listEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunction_argument_listEx; /* Prevent compiler warnings */
    rulefunction_argument_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 101, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"function_argument_list");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end function_argument_list */

/**
 * $ANTLR start function_argument
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:102:1: function_argument : type identifier ;
 */
static void
function_argument(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"function_argument");
    incRuleLevel();
    DBG->location(DBG, 102, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:103:2: ( type identifier )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:103:4: type identifier
        {
            DBG->location(DBG, 103, 4);
            FOLLOWPUSH(FOLLOW_type_in_function_argument216);
            type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunction_argumentEx;
            }

            DBG->location(DBG, 103, 9);
            FOLLOWPUSH(FOLLOW_identifier_in_function_argument218);
            identifier(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunction_argumentEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunction_argumentEx; /* Prevent compiler warnings */
    rulefunction_argumentEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 104, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"function_argument");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end function_argument */

/**
 * $ANTLR start return_type_clause
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:105:1: return_type_clause : 'contained a' type ;
 */
static void
return_type_clause(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"return_type_clause");
    incRuleLevel();
    DBG->location(DBG, 105, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:106:2: ( 'contained a' type )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:106:4: 'contained a' type
        {
            DBG->location(DBG, 106, 4);
             MATCHT(19, &FOLLOW_19_in_return_type_clause228);
            if  (HASEXCEPTION())
            {
                goto rulereturn_type_clauseEx;
            }

            DBG->location(DBG, 106, 18);
            FOLLOWPUSH(FOLLOW_type_in_return_type_clause230);
            type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulereturn_type_clauseEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulereturn_type_clauseEx; /* Prevent compiler warnings */
    rulereturn_type_clauseEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 107, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"return_type_clause");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end return_type_clause */

/**
 * $ANTLR start block_unit
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:108:1: block_unit : 'opened' 'closed' ;
 */
static void
block_unit(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"block_unit");
    incRuleLevel();
    DBG->location(DBG, 108, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:109:2: ( 'opened' 'closed' )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:109:4: 'opened' 'closed'
        {
            DBG->location(DBG, 109, 4);
             MATCHT(23, &FOLLOW_23_in_block_unit240);
            if  (HASEXCEPTION())
            {
                goto ruleblock_unitEx;
            }

            DBG->location(DBG, 109, 13);
             MATCHT(18, &FOLLOW_18_in_block_unit242);
            if  (HASEXCEPTION())
            {
                goto ruleblock_unitEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblock_unitEx; /* Prevent compiler warnings */
    ruleblock_unitEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 109, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"block_unit");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end block_unit */

/**
 * $ANTLR start function_invocation
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:111:1: function_invocation : identifier '(' ( function_invocation_argument_list )? ')' ;
 */
static void
function_invocation(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"function_invocation");
    incRuleLevel();
    DBG->location(DBG, 111, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:112:2: ( identifier '(' ( function_invocation_argument_list )? ')' )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:112:4: identifier '(' ( function_invocation_argument_list )? ')'
        {
            DBG->location(DBG, 112, 4);
            FOLLOWPUSH(FOLLOW_identifier_in_function_invocation252);
            identifier(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunction_invocationEx;
            }

            DBG->location(DBG, 112, 15);
             MATCHT(8, &FOLLOW_8_in_function_invocation254);
            if  (HASEXCEPTION())
            {
                goto rulefunction_invocationEx;
            }

            DBG->location(DBG, 112, 19);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:112:19: ( function_invocation_argument_list )?
            {
                int alt6=2;
                DBG->enterSubRule(DBG, 6);
                DBG->enterDecision(DBG, 6);

                switch ( LA(1) )
                {
                    case CHARACTER_LITERAL:
                    case DECIMAL_NUMBER:
                    	{
                    		alt6=1;
                    	}
                        break;
                }

                DBG->exitDecision(DBG, 6);

                switch (alt6)
                {
            	case 1:
            	    DBG->enterAlt(DBG, 1);

            	    // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:112:19: function_invocation_argument_list
            	    {
            	        DBG->location(DBG, 112, 19);
            	        FOLLOWPUSH(FOLLOW_function_invocation_argument_list_in_function_invocation256);
            	        function_invocation_argument_list(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunction_invocationEx;
            	        }


            	    }
            	    break;

                }
                DBG->exitSubRule(DBG, 6);

            }
            DBG->location(DBG, 112, 54);
             MATCHT(9, &FOLLOW_9_in_function_invocation259);
            if  (HASEXCEPTION())
            {
                goto rulefunction_invocationEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunction_invocationEx; /* Prevent compiler warnings */
    rulefunction_invocationEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 113, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"function_invocation");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end function_invocation */

/**
 * $ANTLR start function_invocation_argument_list
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:114:1: function_invocation_argument_list : ( constant ',' )* constant ;
 */
static void
function_invocation_argument_list(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"function_invocation_argument_list");
    incRuleLevel();
    DBG->location(DBG, 114, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:115:2: ( ( constant ',' )* constant )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:115:4: ( constant ',' )* constant
        {
            DBG->location(DBG, 115, 4);
            // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:115:4: ( constant ',' )*

            DBG->enterSubRule(DBG, 7);

            for (;;)
            {
                int alt7=2;
                DBG->enterDecision(DBG, 7);

                switch ( LA(1) )
                {
                case CHARACTER_LITERAL:
                case DECIMAL_NUMBER:
                	{
                		switch ( LA(2) )
                		{
                		case 10:
                			{
                				alt7=1;
                			}
                		    break;

                		}

                	}
                    break;

                }

                DBG->exitDecision(DBG, 7);

                switch (alt7)
                {
            	case 1:
            	    DBG->enterAlt(DBG, 1);

            	    // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:115:5: constant ','
            	    {
            	        DBG->location(DBG, 115, 5);
            	        FOLLOWPUSH(FOLLOW_constant_in_function_invocation_argument_list270);
            	        constant(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunction_invocation_argument_listEx;
            	        }

            	        DBG->location(DBG, 115, 14);
            	         MATCHT(10, &FOLLOW_10_in_function_invocation_argument_list272);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunction_invocation_argument_listEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */
            DBG->exitSubRule(DBG, 7);

            DBG->location(DBG, 115, 20);
            FOLLOWPUSH(FOLLOW_constant_in_function_invocation_argument_list276);
            constant(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunction_invocation_argument_listEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunction_invocation_argument_listEx; /* Prevent compiler warnings */
    rulefunction_invocation_argument_listEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 116, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"function_invocation_argument_list");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end function_invocation_argument_list */

/**
 * $ANTLR start return
 * /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:120:1: return : 'Alice found' constant ;
 */
static void
return(pMAliceParser ctx)
{
    /* Initialize rule variables
     */

    if ( getRuleLevel()==0 )
    {
    	DBG->commence(DBG);
    }
    DBG->enterRule(DBG, getGrammarFileName(), (const char *)"return");
    incRuleLevel();
    DBG->location(DBG, 120, );

    {
        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:120:8: ( 'Alice found' constant )
        DBG->enterAlt(DBG, 1);

        // /Users/alexrozanski/Imperial/CS2/Labs/MAlice/malice/grammar/MAlice.g:120:10: 'Alice found' constant
        {
            DBG->location(DBG, 120, 10);
             MATCHT(14, &FOLLOW_14_in_return288);
            if  (HASEXCEPTION())
            {
                goto rulereturnEx;
            }

            DBG->location(DBG, 120, 24);
            FOLLOWPUSH(FOLLOW_constant_in_return290);
            constant(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulereturnEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulereturnEx; /* Prevent compiler warnings */
    rulereturnEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    DBG->location(DBG, 121, );

    DBG->exitRule(DBG, getGrammarFileName(), (const char *)"return");
    decRuleLevel();
    if ( getRuleLevel()==0 )
    {
    	DBG->terminate(DBG);
    }


    return ;
}
/* $ANTLR end return */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
