/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g
 *     -                            On : 2012-11-16 18:40:01
 *     -                 for the lexer : MAliceLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MAliceLexer.h"
/* ----------------------------------------- */


/** String literals used by MAliceLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x23, 0x23, 0x23,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x41, 0x6C, 0x69, 0x63, 0x65, 0x20, 0x66, 0x6F, 0x75, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x54, 0x68, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x61, 0x6E, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x62, 0x65, 0x63, 0x61, 0x6D, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x62, 0x65, 0x63, 0x61, 0x75, 0x73, 0x65, 0x20, 0x41, 0x6C, 0x69, 0x63, 0x65, 0x20, 0x77, 0x61, 0x73, 0x20, 0x75, 0x6E, 0x73, 0x75, 0x72, 0x65, 0x20, 0x77, 0x68, 0x69, 0x63, 0x68,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x62, 0x65, 0x63, 0x61, 0x75, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x62, 0x75, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x63, 0x6C, 0x6F, 0x73, 0x65, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x63, 0x6F, 0x6E, 0x74, 0x61, 0x69, 0x6E, 0x65, 0x64, 0x20, 0x61,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x65, 0x6E, 0x6F, 0x75, 0x67, 0x68, 0x20, 0x74, 0x69, 0x6D, 0x65, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x65, 0x76, 0x65, 0x6E, 0x74, 0x75, 0x61, 0x6C, 0x6C, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x6C, 0x65, 0x74, 0x74, 0x65, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x6C, 0x6F, 0x6F, 0x6B, 0x69, 0x6E, 0x67, 0x2D, 0x67, 0x6C, 0x61, 0x73, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x6D, 0x61, 0x79, 0x62, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x6E, 0x75, 0x6D, 0x62, 0x65, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x6F, 0x70, 0x65, 0x6E, 0x65, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_19[]  = { 0x70, 0x65, 0x72, 0x68, 0x61, 0x70, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_20[]  = { 0x72, 0x6F, 0x6F, 0x6D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_21[]  = { 0x73, 0x6F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_22[]  = { 0x74, 0x68, 0x65, 0x6E,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMAliceLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMAliceLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMAliceLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMAliceLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__9    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__10    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__11    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__12    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__13    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__14    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__15    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__16    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__17    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__20    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__21    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__22    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__23    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__24    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__25    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__26    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__27    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__28    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__29    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__30    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__31    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__32    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__33    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__34    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__35    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mT__36    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mLETTER    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mCHARACTER_LITERAL    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mZERO_NUMBER    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mNON_ZERO_DECIMAL_NUMBER    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mNEWLINE    (pMAliceLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pMAliceLexer ctx);
static void	MAliceLexerFree(pMAliceLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
MAliceLexerFree  (pMAliceLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
MAliceLexerReset (pMAliceLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called MAliceLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pMAliceLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pMAliceLexer MAliceLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return MAliceLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called MAliceLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pMAliceLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pMAliceLexer MAliceLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMAliceLexer ctx; // Context structure we will build and return

    ctx = (pMAliceLexer) ANTLR3_CALLOC(1, sizeof(MAliceLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MAliceLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our MAliceLexer interface
     */
    ctx->mT__9	= mT__9;
    ctx->mT__10	= mT__10;
    ctx->mT__11	= mT__11;
    ctx->mT__12	= mT__12;
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mLETTER	= mLETTER;
    ctx->mCHARACTER_LITERAL	= mCHARACTER_LITERAL;
    ctx->mZERO_NUMBER	= mZERO_NUMBER;
    ctx->mNON_ZERO_DECIMAL_NUMBER	= mNON_ZERO_DECIMAL_NUMBER;
    ctx->mNEWLINE	= mNEWLINE;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= MAliceLexerFree;
    ctx->reset          = MAliceLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:6: ( '###' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__9
 *
 * Looks to match the characters the constitute the token T__9
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__9(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__9;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:7:6: ( '###' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:7:8: '###'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__9Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__9Ex; /* Prevent compiler warnings */
    ruleT__9Ex: ;

}
// $ANTLR end T__9

//   Comes from: 8:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__10
 *
 * Looks to match the characters the constitute the token T__10
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__10(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__10;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:8:7: ( '(' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:8:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__10Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__10Ex; /* Prevent compiler warnings */
    ruleT__10Ex: ;

}
// $ANTLR end T__10

//   Comes from: 9:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__11
 *
 * Looks to match the characters the constitute the token T__11
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__11(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__11;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:9:7: ( ')' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:9:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__11Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__11Ex; /* Prevent compiler warnings */
    ruleT__11Ex: ;

}
// $ANTLR end T__11

//   Comes from: 10:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__12
 *
 * Looks to match the characters the constitute the token T__12
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__12(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__12;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:10:7: ( ',' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:10:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__12Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__12Ex; /* Prevent compiler warnings */
    ruleT__12Ex: ;

}
// $ANTLR end T__12

//   Comes from: 11:7: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:11:7: ( '.' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:11:9: '.'
    {
        MATCHC('.');
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 12:7: ( '9' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:12:7: ( '9' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:12:9: '9'
    {
        MATCHC('9');
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 13:7: ( 'Alice found' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:13:7: ( 'Alice found' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:13:9: 'Alice found'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 14:7: ( 'The' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:14:7: ( 'The' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:14:9: 'The'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 15:7: ( 'and' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:15:7: ( 'and' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:15:9: 'and'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 16:7: ( 'became' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:16:7: ( 'became' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:16:9: 'became'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 17:7: ( 'because Alice was unsure which' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:17:7: ( 'because Alice was unsure which' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:17:9: 'because Alice was unsure which'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 18:7: ( 'because' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:18:7: ( 'because' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:18:9: 'because'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 19:7: ( 'but' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:19:7: ( 'but' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:19:9: 'but'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 20:7: ( 'closed' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:20:7: ( 'closed' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:20:9: 'closed'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 21:7: ( 'contained a' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:21:7: ( 'contained a' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:21:9: 'contained a'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 22:7: ( 'enough times' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:22:7: ( 'enough times' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:22:9: 'enough times'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 23:7: ( 'eventually' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:23:7: ( 'eventually' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:23:9: 'eventually'
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 24:7: ( 'letter' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:24:7: ( 'letter' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:24:9: 'letter'
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 25:7: ( 'looking-glass' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:25:7: ( 'looking-glass' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:25:9: 'looking-glass'
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 26:7: ( 'maybe' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:26:7: ( 'maybe' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:26:9: 'maybe'
    {
        MATCHS(lit_15);
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 27:7: ( 'number' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:27:7: ( 'number' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:27:9: 'number'
    {
        MATCHS(lit_16);
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 28:7: ( 'opened' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:28:7: ( 'opened' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:28:9: 'opened'
    {
        MATCHS(lit_17);
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 29:7: ( 'or' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:29:7: ( 'or' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:29:9: 'or'
    {
        MATCHS(lit_18);
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 30:7: ( 'perhaps' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:30:7: ( 'perhaps' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:30:9: 'perhaps'
    {
        MATCHS(lit_19);
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 31:7: ( 'room' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:31:7: ( 'room' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:31:9: 'room'
    {
        MATCHS(lit_20);
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 32:7: ( 'so' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:32:7: ( 'so' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:32:9: 'so'
    {
        MATCHS(lit_21);
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 33:7: ( 'then' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:33:7: ( 'then' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:33:9: 'then'
    {
        MATCHS(lit_22);
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 34:7: ( '~' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:34:7: ( '~' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:34:9: '~'
    {
        MATCHC('~');
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 206:8: ( ( 'a' .. 'z' | 'A' .. 'Z' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LETTER
 *
 * Looks to match the characters the constitute the token LETTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLETTER(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LETTER;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:206:8: ( ( 'a' .. 'z' | 'A' .. 'Z' ) )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleLETTEREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLETTEREx; /* Prevent compiler warnings */
    ruleLETTEREx: ;

}
// $ANTLR end LETTER

//   Comes from: 210:2: ( '\\'' LETTER '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHARACTER_LITERAL
 *
 * Looks to match the characters the constitute the token CHARACTER_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHARACTER_LITERAL(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHARACTER_LITERAL;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:210:2: ( '\\'' LETTER '\\'' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:210:4: '\\'' LETTER '\\''
    {
        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


        /* 210:4: '\\'' LETTER '\\'' */
        mLETTER(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }



        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHARACTER_LITERALEx; /* Prevent compiler warnings */
    ruleCHARACTER_LITERALEx: ;

}
// $ANTLR end CHARACTER_LITERAL

//   Comes from: 216:2: ( '0' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ZERO_NUMBER
 *
 * Looks to match the characters the constitute the token ZERO_NUMBER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mZERO_NUMBER(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ZERO_NUMBER;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:216:2: ( '0' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:216:4: '0'
    {
        MATCHC('0');
        if  (HASEXCEPTION())
        {
            goto ruleZERO_NUMBEREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleZERO_NUMBEREx; /* Prevent compiler warnings */
    ruleZERO_NUMBEREx: ;

}
// $ANTLR end ZERO_NUMBER

//   Comes from: 220:2: ( '1' .. '9' ( '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NON_ZERO_DECIMAL_NUMBER
 *
 * Looks to match the characters the constitute the token NON_ZERO_DECIMAL_NUMBER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNON_ZERO_DECIMAL_NUMBER(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NON_ZERO_DECIMAL_NUMBER;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:220:2: ( '1' .. '9' ( '0' .. '9' )* )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:220:4: '1' .. '9' ( '0' .. '9' )*
    {
        MATCHRANGE('1', '9');
        if  (HASEXCEPTION())
        {
            goto ruleNON_ZERO_DECIMAL_NUMBEREx;
        }


        // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:220:13: ( '0' .. '9' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1)
            {
        	case 1:
        	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleNON_ZERO_DECIMAL_NUMBEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNON_ZERO_DECIMAL_NUMBEREx; /* Prevent compiler warnings */
    ruleNON_ZERO_DECIMAL_NUMBEREx: ;

}
// $ANTLR end NON_ZERO_DECIMAL_NUMBER

//   Comes from: 223:9: ( ( '\\r' )? '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NEWLINE
 *
 * Looks to match the characters the constitute the token NEWLINE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNEWLINE(pMAliceLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NEWLINE;


    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:223:9: ( ( '\\r' )? '\\n' )
    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:223:11: ( '\\r' )? '\\n'
    {
        // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:223:11: ( '\\r' )?
        {
            int alt2=2;
            switch ( LA(1) )
            {
                case '\r':
                	{
                		alt2=1;
                	}
                    break;
            }

            switch (alt2)
            {
        	case 1:
        	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:223:11: '\\r'
        	    {
        	        MATCHC('\r');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNEWLINEEx;
        	        }


        	    }
        	    break;

            }
        }

        MATCHC('\n');
        if  (HASEXCEPTION())
        {
            goto ruleNEWLINEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEWLINEEx; /* Prevent compiler warnings */
    ruleNEWLINEEx: ;

}
// $ANTLR end NEWLINE

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pMAliceLexer ctx)
{
    {
        //  C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:8: ( T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | LETTER | CHARACTER_LITERAL | ZERO_NUMBER | NON_ZERO_DECIMAL_NUMBER | NEWLINE )

        ANTLR3_UINT32 alt3;

        alt3=33;

        switch ( LA(1) )
        {
        case '#':
        	{
        		alt3=1;
        	}
            break;
        case '(':
        	{
        		alt3=2;
        	}
            break;
        case ')':
        	{
        		alt3=3;
        	}
            break;
        case ',':
        	{
        		alt3=4;
        	}
            break;
        case '.':
        	{
        		alt3=5;
        	}
            break;
        case '9':
        	{
        		switch ( LA(2) )
        		{
        		case '0':
        		case '1':
        		case '2':
        		case '3':
        		case '4':
        		case '5':
        		case '6':
        		case '7':
        		case '8':
        		case '9':
        			{
        				alt3=32;
        			}
        		    break;

        		default:
        		    alt3=6;
        		}

        	}
            break;
        case 'A':
        	{
        		switch ( LA(2) )
        		{
        		case 'l':
        			{
        				alt3=7;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'T':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				alt3=8;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'a':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				alt3=9;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'b':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'c':
        					{
        						switch ( LA(4) )
        						{
        						case 'a':
        							{
        								switch ( LA(5) )
        								{
        								case 'm':
        									{
        										alt3=10;
        									}
        								    break;
        								case 'u':
        									{
        										switch ( LA(6) )
        										{
        										case 's':
        											{
        												switch ( LA(7) )
        												{
        												case 'e':
        													{
        														switch ( LA(8) )
        														{
        														case ' ':
        															{
        																alt3=11;
        															}
        														    break;

        														default:
        														    alt3=12;
        														}

        													}
        												    break;

        												default:
        												    CONSTRUCTEX();
        												    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        												    EXCEPTION->message      = (void *)"";
        												    EXCEPTION->decisionNum  = 3;
        												    EXCEPTION->state        = 51;


        												    goto ruleTokensEx;

        												}

        											}
        										    break;

        										default:
        										    CONSTRUCTEX();
        										    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        										    EXCEPTION->message      = (void *)"";
        										    EXCEPTION->decisionNum  = 3;
        										    EXCEPTION->state        = 50;


        										    goto ruleTokensEx;

        										}

        									}
        								    break;

        								default:
        								    CONSTRUCTEX();
        								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        								    EXCEPTION->message      = (void *)"";
        								    EXCEPTION->decisionNum  = 3;
        								    EXCEPTION->state        = 48;


        								    goto ruleTokensEx;

        								}

        							}
        						    break;

        						default:
        						    CONSTRUCTEX();
        						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        						    EXCEPTION->message      = (void *)"";
        						    EXCEPTION->decisionNum  = 3;
        						    EXCEPTION->state        = 47;


        						    goto ruleTokensEx;

        						}

        					}
        				    break;

        				default:
        				    CONSTRUCTEX();
        				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        				    EXCEPTION->message      = (void *)"";
        				    EXCEPTION->decisionNum  = 3;
        				    EXCEPTION->state        = 31;


        				    goto ruleTokensEx;

        				}

        			}
        		    break;
        		case 'u':
        			{
        				alt3=13;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'l':
        			{
        				alt3=14;
        			}
        		    break;
        		case 'o':
        			{
        				alt3=15;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'e':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				alt3=16;
        			}
        		    break;
        		case 'v':
        			{
        				alt3=17;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'l':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				alt3=18;
        			}
        		    break;
        		case 'o':
        			{
        				alt3=19;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'm':
        	{
        		switch ( LA(2) )
        		{
        		case 'a':
        			{
        				alt3=20;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'n':
        	{
        		switch ( LA(2) )
        		{
        		case 'u':
        			{
        				alt3=21;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'o':
        	{
        		switch ( LA(2) )
        		{
        		case 'p':
        			{
        				alt3=22;
        			}
        		    break;
        		case 'r':
        			{
        				alt3=23;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				alt3=24;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 'r':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				alt3=25;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 's':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				alt3=26;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case 't':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				alt3=27;
        			}
        		    break;

        		default:
        		    alt3=29;
        		}

        	}
            break;
        case '~':
        	{
        		alt3=28;
        	}
            break;
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case 'd':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'q':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt3=29;
        	}
            break;
        case '\'':
        	{
        		alt3=30;
        	}
            break;
        case '0':
        	{
        		alt3=31;
        	}
            break;
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        	{
        		alt3=32;
        	}
            break;
        case '\n':
        case '\r':
        	{
        		alt3=33;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 3;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt3)
        {
    	case 1:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:10: T__9
    	    {
    	        /* 1:10: T__9 */
    	        mT__9(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:15: T__10
    	    {
    	        /* 1:15: T__10 */
    	        mT__10(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:21: T__11
    	    {
    	        /* 1:21: T__11 */
    	        mT__11(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:27: T__12
    	    {
    	        /* 1:27: T__12 */
    	        mT__12(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:33: T__13
    	    {
    	        /* 1:33: T__13 */
    	        mT__13(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:39: T__14
    	    {
    	        /* 1:39: T__14 */
    	        mT__14(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:45: T__15
    	    {
    	        /* 1:45: T__15 */
    	        mT__15(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:51: T__16
    	    {
    	        /* 1:51: T__16 */
    	        mT__16(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:57: T__17
    	    {
    	        /* 1:57: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:63: T__18
    	    {
    	        /* 1:63: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:69: T__19
    	    {
    	        /* 1:69: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:75: T__20
    	    {
    	        /* 1:75: T__20 */
    	        mT__20(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:81: T__21
    	    {
    	        /* 1:81: T__21 */
    	        mT__21(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:87: T__22
    	    {
    	        /* 1:87: T__22 */
    	        mT__22(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:93: T__23
    	    {
    	        /* 1:93: T__23 */
    	        mT__23(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:99: T__24
    	    {
    	        /* 1:99: T__24 */
    	        mT__24(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:105: T__25
    	    {
    	        /* 1:105: T__25 */
    	        mT__25(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:111: T__26
    	    {
    	        /* 1:111: T__26 */
    	        mT__26(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:117: T__27
    	    {
    	        /* 1:117: T__27 */
    	        mT__27(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:123: T__28
    	    {
    	        /* 1:123: T__28 */
    	        mT__28(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:129: T__29
    	    {
    	        /* 1:129: T__29 */
    	        mT__29(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:135: T__30
    	    {
    	        /* 1:135: T__30 */
    	        mT__30(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:141: T__31
    	    {
    	        /* 1:141: T__31 */
    	        mT__31(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:147: T__32
    	    {
    	        /* 1:147: T__32 */
    	        mT__32(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:153: T__33
    	    {
    	        /* 1:153: T__33 */
    	        mT__33(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:159: T__34
    	    {
    	        /* 1:159: T__34 */
    	        mT__34(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:165: T__35
    	    {
    	        /* 1:165: T__35 */
    	        mT__35(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:171: T__36
    	    {
    	        /* 1:171: T__36 */
    	        mT__36(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:177: LETTER
    	    {
    	        /* 1:177: LETTER */
    	        mLETTER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:184: CHARACTER_LITERAL
    	    {
    	        /* 1:184: CHARACTER_LITERAL */
    	        mCHARACTER_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:202: ZERO_NUMBER
    	    {
    	        /* 1:202: ZERO_NUMBER */
    	        mZERO_NUMBER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:214: NON_ZERO_DECIMAL_NUMBER
    	    {
    	        /* 1:214: NON_ZERO_DECIMAL_NUMBER */
    	        mNON_ZERO_DECIMAL_NUMBER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // C:\\Code\\MaliceFinal\\malice\\grammar\\MAlice.g:1:238: NEWLINE
    	    {
    	        /* 1:238: NEWLINE */
    	        mNEWLINE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
