/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /homes/anr11/CS2/Labs/malice/grammar/MAlice.g
 *     -                            On : 2012-11-20 17:00:29
 *     -                for the parser : MAliceParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
MAliceParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pMAliceParser, which is returned from a call to MAliceParserNew().
 *
 * The methods in pMAliceParser are  as follows:
 *
 *  - 
 void
      pMAliceParser->program(pMAliceParser)
 *  - 
 void
      pMAliceParser->type(pMAliceParser)
 *  - 
 void
      pMAliceParser->constant(pMAliceParser)
 *  - 
 void
      pMAliceParser->function(pMAliceParser)
 *  - 
 void
      pMAliceParser->procedure(pMAliceParser)
 *  - 
 void
      pMAliceParser->declaration_argument_list(pMAliceParser)
 *  - 
 void
      pMAliceParser->block(pMAliceParser)
 *  - 
 void
      pMAliceParser->body(pMAliceParser)
 *  - 
 void
      pMAliceParser->declaration_argument(pMAliceParser)
 *  - 
 void
      pMAliceParser->proc_func_invocation(pMAliceParser)
 *  - 
 void
      pMAliceParser->assignment(pMAliceParser)
 *  - 
 void
      pMAliceParser->declaration_separator(pMAliceParser)
 *  - 
 void
      pMAliceParser->statement_list(pMAliceParser)
 *  - 
 void
      pMAliceParser->statement_component(pMAliceParser)
 *  - 
 void
      pMAliceParser->return_statement(pMAliceParser)
 *  - 
 void
      pMAliceParser->while_loop(pMAliceParser)
 *  - 
 void
      pMAliceParser->if_block(pMAliceParser)
 *  - 
 void
      pMAliceParser->else_block(pMAliceParser)
 *  - 
 void
      pMAliceParser->variable_declaration(pMAliceParser)
 *  - 
 void
      pMAliceParser->input_statement(pMAliceParser)
 *  - 
 void
      pMAliceParser->io_statement(pMAliceParser)
 *  - 
 void
      pMAliceParser->print_statement(pMAliceParser)
 *  - 
 void
      pMAliceParser->stdin_statement(pMAliceParser)
 *  - 
 void
      pMAliceParser->stdout_lvalue(pMAliceParser)
 *  - 
 void
      pMAliceParser->expression(pMAliceParser)
 *  - 
 void
      pMAliceParser->assignment_expr(pMAliceParser)
 *  - 
 void
      pMAliceParser->lvalue(pMAliceParser)
 *  - 
 void
      pMAliceParser->additive_expr(pMAliceParser)
 *  - 
 void
      pMAliceParser->multiplicactive_expr(pMAliceParser)
 *  - 
 void
      pMAliceParser->bitwise_expr(pMAliceParser)
 *  - 
 void
      pMAliceParser->unary_expr(pMAliceParser)
 *  - 
 void
      pMAliceParser->boolean_expression(pMAliceParser)
 *  - 
 void
      pMAliceParser->single_boolean_expression(pMAliceParser)
 *  - 
 void
      pMAliceParser->identifier(pMAliceParser)
 *  - 
 void
      pMAliceParser->number_literal(pMAliceParser)
 *  - 
 void
      pMAliceParser->null_statement(pMAliceParser)
 * 
 * 
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_MAliceParser_H
#define _MAliceParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct MAliceParser_Ctx_struct MAliceParser, * pMAliceParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */


/** Context tracking structure for 
MAliceParser

 */
struct MAliceParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     void
     (*program)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*type)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*constant)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*function)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*procedure)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*declaration_argument_list)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*block)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*body)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*declaration_argument)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*proc_func_invocation)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*assignment)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*declaration_separator)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*statement_list)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*statement_component)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*return_statement)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*while_loop)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*if_block)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*else_block)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*variable_declaration)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*input_statement)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*io_statement)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*print_statement)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*stdin_statement)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*stdout_lvalue)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*expression)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*assignment_expr)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*lvalue)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*additive_expr)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*multiplicactive_expr)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*bitwise_expr)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*unary_expr)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*boolean_expression)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*single_boolean_expression)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*identifier)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*number_literal)	(struct MAliceParser_Ctx_struct * ctx);

     void
     (*null_statement)	(struct MAliceParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred1_MAlice)	(struct MAliceParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred2_MAlice)	(struct MAliceParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred3_MAlice)	(struct MAliceParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred4_MAlice)	(struct MAliceParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct MAliceParser_Ctx_struct * ctx);
    void	    (*free)   (struct MAliceParser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pMAliceParser MAliceParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pMAliceParser MAliceParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define ALICEFOUND      4
#define AND      5
#define BANG      6
#define BECAME      7
#define BUT      8
#define CHARACTER_LITERAL      9
#define CLOSED      10
#define COMMA      11
#define COMMENT      12
#define FULL_STOP      13
#define LETTER      14
#define LPAREN      15
#define MINUS      16
#define NEWLINE      17
#define NON_ZERO_NUMBER      18
#define OPENED      19
#define PLUS      20
#define RPAREN      21
#define SAIDALICE      22
#define SPOKE      23
#define STRING_LITERAL      24
#define THELOOKINGGLASS      25
#define THEN      26
#define THEROOM      27
#define TILDE      28
#define UNDERSCORE      29
#define WASA      30
#define WS      31
#define ZERO_NUMBER      32
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for MAliceParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
