/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g
 *     -                            On : 2012-11-15 12:23:14
 *     -                for the parser : MAliceParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MAliceParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMAliceParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMAliceParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMAliceParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMAliceParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   MAliceParserTokenNames[10+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'+'",
        (pANTLR3_UINT8) "'-'",
        (pANTLR3_UINT8) "'='"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 MAliceParser_prog_return
	prog    (pMAliceParser ctx);
static 
 MAliceParser_stat_return
	stat    (pMAliceParser ctx);
static 
 MAliceParser_expr_return
	expr    (pMAliceParser ctx);
static 
 MAliceParser_multExpr_return
	multExpr    (pMAliceParser ctx);
static 
 MAliceParser_atom_return
	atom    (pMAliceParser ctx);
static void	MAliceParserFree(pMAliceParser ctx);
static void     MAliceParserReset (pMAliceParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new MAliceParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMAliceParser
MAliceParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return MAliceParserNewSSD(instream, NULL);
}

/** \brief Create a new MAliceParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMAliceParser
MAliceParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMAliceParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pMAliceParser) ANTLR3_CALLOC(1, sizeof(MAliceParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MAliceParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our MAliceParser interface
     */
    ctx->prog	= prog;
    ctx->stat	= stat;
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->free			= MAliceParserFree;
    ctx->reset			= MAliceParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = MAliceParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
MAliceParserReset (pMAliceParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 MAliceParserFree(pMAliceParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return MAliceParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stat_in_prog35  */
static	ANTLR3_BITWORD FOLLOW_stat_in_prog35_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000172) };
static  ANTLR3_BITSET_LIST FOLLOW_stat_in_prog35	= { FOLLOW_stat_in_prog35_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stat49  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stat49_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stat49	= { FOLLOW_expr_in_stat49_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stat51  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stat51_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stat51	= { FOLLOW_NEWLINE_in_stat51_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stat67  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stat67_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stat67	= { FOLLOW_ID_in_stat67_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_stat69  */
static	ANTLR3_BITWORD FOLLOW_13_in_stat69_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000130) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_stat69	= { FOLLOW_13_in_stat69_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stat71  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stat71_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stat71	= { FOLLOW_expr_in_stat71_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stat73  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stat73_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stat73	= { FOLLOW_NEWLINE_in_stat73_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stat88  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stat88_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stat88	= { FOLLOW_NEWLINE_in_stat88_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr112  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr112_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001802) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr112	= { FOLLOW_multExpr_in_expr112_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_expr116  */
static	ANTLR3_BITWORD FOLLOW_11_in_expr116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000130) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_expr116	= { FOLLOW_11_in_expr116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_expr119  */
static	ANTLR3_BITWORD FOLLOW_12_in_expr119_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000130) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_expr119	= { FOLLOW_12_in_expr119_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr123  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr123_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001802) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr123	= { FOLLOW_multExpr_in_expr123_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr136  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr136_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr136	= { FOLLOW_atom_in_multExpr136_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_multExpr139  */
static	ANTLR3_BITWORD FOLLOW_10_in_multExpr139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000130) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_multExpr139	= { FOLLOW_10_in_multExpr139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr142  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr142_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000402) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr142	= { FOLLOW_atom_in_multExpr142_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom154  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom154_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom154	= { FOLLOW_INT_in_atom154_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom159  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom159	= { FOLLOW_ID_in_atom159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_atom164  */
static	ANTLR3_BITWORD FOLLOW_8_in_atom164_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000130) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_atom164	= { FOLLOW_8_in_atom164_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom167  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom167_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom167	= { FOLLOW_expr_in_atom167_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_atom169  */
static	ANTLR3_BITWORD FOLLOW_9_in_atom169_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_atom169	= { FOLLOW_9_in_atom169_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start prog
 * C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:9:1: prog : ( stat )+ ;
 */
static MAliceParser_prog_return
prog(pMAliceParser ctx)
{
    MAliceParser_prog_return retval;


    CommonTree root_0;

    MAliceParser_stat_return stat1;
    #undef	RETURN_TYPE_stat1
    #define	RETURN_TYPE_stat1 MAliceParser_stat_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stat1.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:9:6: ( ( stat )+ )
        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:9:8: ( stat )+
        {
            root_0 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));


            // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:9:8: ( stat )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	switch ( LA(1) )
            	{
            	case ID:
            	case INT:
            	case NEWLINE:
            	case 8:
            		{
            			alt1=1;
            		}
            	    break;

            	}

            	switch (alt1)
            	{
            	    case 1:
            	        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:9:10: stat
            	        {
            	            FOLLOWPUSH(FOLLOW_stat_in_prog35);
            	            stat1=stat(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, stat1.tree);

            	            {
            	                print (stat1.tree).toStringTree();
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (CommonTree)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (CommonTree)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */

/**
 * $ANTLR start stat
 * C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:11:1: stat : ( expr NEWLINE -> expr | ID '=' expr NEWLINE -> ^( '=' ID expr ) | NEWLINE ->);
 */
static MAliceParser_stat_return
stat(pMAliceParser ctx)
{
    MAliceParser_stat_return retval;


    CommonTree root_0;

    pANTLR3_COMMON_TOKEN    NEWLINE3;
    pANTLR3_COMMON_TOKEN    ID4;
    pANTLR3_COMMON_TOKEN    char_literal5;
    pANTLR3_COMMON_TOKEN    NEWLINE7;
    pANTLR3_COMMON_TOKEN    NEWLINE8;
    MAliceParser_expr_return expr2;
    #undef	RETURN_TYPE_expr2
    #define	RETURN_TYPE_expr2 MAliceParser_expr_return

    MAliceParser_expr_return expr6;
    #undef	RETURN_TYPE_expr6
    #define	RETURN_TYPE_expr6 MAliceParser_expr_return

    CommonTree NEWLINE3_tree;
    CommonTree ID4_tree;
    CommonTree char_literal5_tree;
    CommonTree NEWLINE7_tree;
    CommonTree NEWLINE8_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_13;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    NEWLINE3       = NULL;
    ID4       = NULL;
    char_literal5       = NULL;
    NEWLINE7       = NULL;
    NEWLINE8       = NULL;
    expr2.tree = NULL;

    expr6.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    NEWLINE3_tree   = NULL;
    ID4_tree   = NULL;
    char_literal5_tree   = NULL;
    NEWLINE7_tree   = NULL;
    NEWLINE8_tree   = NULL;

    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_13   = NULL;
    #define CREATE_stream_13  if (stream_13 == NULL) {stream_13 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 13"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:11:6: ( expr NEWLINE -> expr | ID '=' expr NEWLINE -> ^( '=' ID expr ) | NEWLINE ->)

            ANTLR3_UINT32 alt2;

            alt2=3;

            switch ( LA(1) )
            {
            case INT:
            case 8:
            	{
            		alt2=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case 13:
            			{
            				alt2=2;
            			}
            		    break;
            		case NEWLINE:
            		case 10:
            		case 11:
            		case 12:
            			{
            				alt2=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 2;


            		    goto rulestatEx;

            		}

            	}
                break;
            case NEWLINE:
            	{
            		alt2=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulestatEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:11:8: expr NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stat49);
        	        expr2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr2.tree, NULL);

        	        NEWLINE3 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stat51);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE3, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 11:28: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:12:4: ID '=' expr NEWLINE
        	    {
        	        ID4 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stat67);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID4, NULL);


        	        char_literal5 = (pANTLR3_COMMON_TOKEN) MATCHT(13, &FOLLOW_13_in_stat69);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }
        	         
        	        CREATE_stream_13; stream_13->add(stream_13, char_literal5, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stat71);
        	        expr6=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr6.tree, NULL);

        	        NEWLINE7 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stat73);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE7, NULL);


        	        /* AST REWRITE
        	         * elements          : ID, 13, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 12:24: -> ^( '=' ID expr )
        	        	{
        	        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:12:27: ^( '=' ID expr )
        	        	    {
        	        	        CommonTree root_1 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (CommonTree)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_13 == NULL ? NULL : stream_13->nextNode(stream_13)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:13:4: NEWLINE
        	    {
        	        NEWLINE8 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stat88);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestatEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE8, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 13:24: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestatEx; /* Prevent compiler warnings */
    rulestatEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (CommonTree)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_13 != NULL) stream_13->free(stream_13);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (CommonTree)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stat */

/**
 * $ANTLR start expr
 * C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:1: expr : multExpr ( ( '+' ^| '-' ^) multExpr )* ;
 */
static MAliceParser_expr_return
expr(pMAliceParser ctx)
{
    MAliceParser_expr_return retval;


    CommonTree root_0;

    pANTLR3_COMMON_TOKEN    char_literal10;
    pANTLR3_COMMON_TOKEN    char_literal11;
    MAliceParser_multExpr_return multExpr9;
    #undef	RETURN_TYPE_multExpr9
    #define	RETURN_TYPE_multExpr9 MAliceParser_multExpr_return

    MAliceParser_multExpr_return multExpr12;
    #undef	RETURN_TYPE_multExpr12
    #define	RETURN_TYPE_multExpr12 MAliceParser_multExpr_return

    CommonTree char_literal10_tree;
    CommonTree char_literal11_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal10       = NULL;
    char_literal11       = NULL;
    multExpr9.tree = NULL;

    multExpr12.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal10_tree   = NULL;
    char_literal11_tree   = NULL;


    retval.tree  = NULL;

    {
        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:6: ( multExpr ( ( '+' ^| '-' ^) multExpr )* )
        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:8: multExpr ( ( '+' ^| '-' ^) multExpr )*
        {
            root_0 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_expr112);
            multExpr9=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr9.tree);

            // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:17: ( ( '+' ^| '-' ^) multExpr )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case 11:
                case 12:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:18: ( '+' ^| '-' ^) multExpr
            	    {
            	        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:18: ( '+' ^| '-' ^)
            	        {
            	            int alt3=2;
            	            switch ( LA(1) )
            	            {
            	            case 11:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;
            	            case 12:
            	            	{
            	            		alt3=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 3;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:19: '+' ^
            	        	    {
            	        	        char_literal10 = (pANTLR3_COMMON_TOKEN) MATCHT(11, &FOLLOW_11_in_expr116);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        char_literal10_tree = 
            	        	        (CommonTree)(ADAPTOR->create(ADAPTOR, char_literal10))
            	        	        ;
            	        	        root_0 = (CommonTree)(ADAPTOR->becomeRoot(ADAPTOR, char_literal10_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:16:24: '-' ^
            	        	    {
            	        	        char_literal11 = (pANTLR3_COMMON_TOKEN) MATCHT(12, &FOLLOW_12_in_expr119);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        char_literal11_tree = 
            	        	        (CommonTree)(ADAPTOR->create(ADAPTOR, char_literal11))
            	        	        ;
            	        	        root_0 = (CommonTree)(ADAPTOR->becomeRoot(ADAPTOR, char_literal11_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_expr123);
            	        multExpr12=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr12.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (CommonTree)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (CommonTree)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:19:1: multExpr : atom ( '*' ^ atom )* ;
 */
static MAliceParser_multExpr_return
multExpr(pMAliceParser ctx)
{
    MAliceParser_multExpr_return retval;


    CommonTree root_0;

    pANTLR3_COMMON_TOKEN    char_literal14;
    MAliceParser_atom_return atom13;
    #undef	RETURN_TYPE_atom13
    #define	RETURN_TYPE_atom13 MAliceParser_atom_return

    MAliceParser_atom_return atom15;
    #undef	RETURN_TYPE_atom15
    #define	RETURN_TYPE_atom15 MAliceParser_atom_return

    CommonTree char_literal14_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal14       = NULL;
    atom13.tree = NULL;

    atom15.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal14_tree   = NULL;


    retval.tree  = NULL;

    {
        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:20:2: ( atom ( '*' ^ atom )* )
        // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:20:4: atom ( '*' ^ atom )*
        {
            root_0 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr136);
            atom13=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom13.tree);

            // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:20:9: ( '*' ^ atom )*

            for (;;)
            {
                int alt5=2;
                switch ( LA(1) )
                {
                case 10:
                	{
                		alt5=1;
                	}
                    break;

                }

                switch (alt5)
                {
            	case 1:
            	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:20:10: '*' ^ atom
            	    {
            	        char_literal14 = (pANTLR3_COMMON_TOKEN) MATCHT(10, &FOLLOW_10_in_multExpr139);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        char_literal14_tree = 
            	        (CommonTree)(ADAPTOR->create(ADAPTOR, char_literal14))
            	        ;
            	        root_0 = (CommonTree)(ADAPTOR->becomeRoot(ADAPTOR, char_literal14_tree, root_0));


            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr142);
            	        atom15=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom15.tree);

            	    }
            	    break;

            	default:
            	    goto loop5;	/* break out of the loop */
            	    break;
                }
            }
            loop5: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (CommonTree)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (CommonTree)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:23:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static MAliceParser_atom_return
atom(pMAliceParser ctx)
{
    MAliceParser_atom_return retval;


    CommonTree root_0;

    pANTLR3_COMMON_TOKEN    INT16;
    pANTLR3_COMMON_TOKEN    ID17;
    pANTLR3_COMMON_TOKEN    char_literal18;
    pANTLR3_COMMON_TOKEN    char_literal20;
    MAliceParser_expr_return expr19;
    #undef	RETURN_TYPE_expr19
    #define	RETURN_TYPE_expr19 MAliceParser_expr_return

    CommonTree INT16_tree;
    CommonTree ID17_tree;
    CommonTree char_literal18_tree;
    CommonTree char_literal20_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT16       = NULL;
    ID17       = NULL;
    char_literal18       = NULL;
    char_literal20       = NULL;
    expr19.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT16_tree   = NULL;
    ID17_tree   = NULL;
    char_literal18_tree   = NULL;
    char_literal20_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:23:6: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt6;

            alt6=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt6=1;
            	}
                break;
            case ID:
            	{
            		alt6=2;
            	}
                break;
            case 8:
            	{
            		alt6=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:23:8: INT
        	    {
        	        root_0 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));


        	        INT16 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom154);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT16_tree = (CommonTree)(ADAPTOR->create(ADAPTOR, INT16));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT16_tree);


        	    }
        	    break;
        	case 2:
        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:24:4: ID
        	    {
        	        root_0 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));


        	        ID17 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom159);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID17_tree = (CommonTree)(ADAPTOR->create(ADAPTOR, ID17));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID17_tree);


        	    }
        	    break;
        	case 3:
        	    // C:\\Code\\MaliceFinal\\malice\\ANTLR\\MAlice.g:25:4: '(' ! expr ')' !
        	    {
        	        root_0 = (CommonTree)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal18 = (pANTLR3_COMMON_TOKEN) MATCHT(8, &FOLLOW_8_in_atom164);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom167);
        	        expr19=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr19.tree);

        	        char_literal20 = (pANTLR3_COMMON_TOKEN) MATCHT(9, &FOLLOW_9_in_atom169);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (CommonTree)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (CommonTree)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
